### ISSUE TITLE
Continuous integration setup (build)

### ISSUE THREAD

**Issue by paulvazbad** [RoBorregos/Robocup-Home#64]
Find a way to automate building and testing the develop branch
Deliverable: testing examples in the main engine package and docs on how to CI the project

**Comment by tomvik** [comment]
@paulvazbad Maybe for the CI, could be as simple as using Github Workflows. A working example is in [RoBorrego's webpage](https://github.com/RoBorregos/roborregos-web/blob/develop/.github/workflows/node.js.yml)

The result is that everytime anyone makes a PR to develop, basically these two commands will run:
```
yarn install
yarn test
```
* It looks like this when you make a PR (ignore the blocking due to a lack of reviewers)
![image](https://user-images.githubusercontent.com/13770244/95242694-29769d80-07d5-11eb-86fc-b01ebb415cfa.png)

* One can go and check more info about the pipeline
![image](https://user-images.githubusercontent.com/13770244/95242732-385d5000-07d5-11eb-9db4-44fb431f250a.png)

* Once it's finished, it looks like this
![image](https://user-images.githubusercontent.com/13770244/95242883-6e023900-07d5-11eb-8b96-f8a67146aafd.png)

I think this could be adapted to be something like:
```
// install dependencies
catkin_make // to make sure it builds
// command(s) to perform style checking
// command to perform tests
```

**Comment by paulvazbad** [comment]
and `catkin_make run_tests` can be used to perform the tests, I like your idea @tomvik !

**Comment by paulvazbad** [comment]
TODO: update action to include unit testing and integration testing

**Comment by tomvik** [comment]
Will open a second issue for the testing
