### ISSUE TITLE
Integrate arm to the robot

### ISSUE THREAD

**Issue by paulvazbad** [RoBorregos/Robocup-Home#77]
Deliverable: CAD of the robot including the new design arm.

**Comment by AminMendez** [comment]
The integration of the Arm/Elevator to the base still in progresss. We do several modification to the chasis structue, and we open the posibility to the arm to reach the floor. Also we modificated the Scara Arm to satisify the challenges and mantain stability, such as lenght, supports and arm base. 

We have some problems to place the kinect base and it stilled floated, but we are going to design a 3d printed base from the chasis in order to place it.

![Scara Modification2](https://user-images.githubusercontent.com/47193853/97252858-97105b00-17d0-11eb-975e-41ac32a99946.JPG)
![Scara Modification](https://user-images.githubusercontent.com/47193853/97252859-97a8f180-17d0-11eb-94a6-33e2e75f024f.JPG)
![@Home Robot (26-10-2020)](https://user-images.githubusercontent.com/47193853/97252860-97a8f180-17d0-11eb-8777-ae17bc3250cd.JPG)
